on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enter the project directory
        run: cd web

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/web"
          REMOTE_HOST: minha-rotina.glbessa.dev.br
          REMOTE_USER: minha-rotina-web
          REMOTE_PORT: 22
          TARGET: web
          EXCLUDE: ".env, storage, storage/app/, public/storage/, public/storage, storage/logs, node_modules"

      - name: Post deploy
        uses: appleboy/ssh-action@master
        with:
          host: minha-rotina.glbessa.dev.br
          username: minha-rotina-web
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd web
            php8.4 artisan migrate --force
            php8.4 artisan optimize

      - name: Reset opcache
        run: wget -q -O /dev/null https://minha-rotina.glbessa.dev.br/reset-op-cache-QuLkiL5e6up8lNFk9tYq
